### ISSUE TITLE
《不学习何以强国》在Chrome for Mac上不能刷视频，其他功能正常

### ISSUE THREAD

**Issue by James-Harden-13-R** [TechXueXi/techxuexi-js#1]
油猴脚本《不学习何以强国》在Chrome for Mac上不能刷视频，左下角一直显示“正在初始化”，其他功能正常。
且已经按照“视频不能自动播放”的教程修改了网页权限，允许弹出窗口。

Mac Monterey 12.0.1
Google Chrome Version 95.0.4638.54 (Official Build) (x86_64)

**Comment by chunguangtian** [comment]
视频播放完成后不能自动关闭，就不能自动播放下一个了

**Comment by techxuexi21** [comment]
这个在最新版已经修复。如果还是出现，请重新提交issue
