### ISSUE TITLE
如果脚本坚持每分钟刷新一次主页，是否可以保活cookies，使得不用每天重新扫码登录？

### ISSUE THREAD

**Issue by MargaretteMoss** [TechXueXi/techxuexi-js#15]
如果脚本坚持每分钟刷新一次主页，是否可以保活cookies，使得不用每天重新扫码登录？

如果可以的话，希望优化代码支持该功能，谢谢。

**Comment by asnfohsdgfbkxcv** [comment]
自己装网页刷新的扩展不就可以啦？

**Comment by sharkAndshark** [comment]
单独开个选项卡在控制台写两行js保活也够了应该

**Comment by MargaretteMoss** [comment]
> 自己装网页刷新的扩展不就可以啦？

https://chrome.google.com/webstore/detail/tab-auto-refresh/oomoeacogjkolheacgdkkkhbjipaomkn

这个可以

**Comment by haipengzzz** [comment]
@MargaretteMoss  大佬通过网页的不断刷新是否可以保活？
