### ISSUE TITLE
左上角没有开始按钮

### ISSUE THREAD

**Issue by YYDDS** [TechXueXi/techxuexi-js#20]
今天更新12.16用油猴使用脚本左上角没有开始按钮，以前都可以用。

**Comment by dsd137** [comment]
21号左上角还是没按钮，显示开始学习的界面，如果修复了直接发qq邮件给我吧

**Comment by TheLostParadise** [comment]
23号左上角依然没有按钮。

**Comment by kirakira2021** [comment]
> 23号左上角依然没有按钮。

登录之后的界面按F12,弹出的界面看看有没有红字, 有的话截图看看

**Comment by TheLostParadise** [comment]
> > 23号左上角依然没有按钮。
> 
> 登录之后的界面按F12,弹出的界面看看有没有红字, 有的话截图看看
![11](https://user-images.githubusercontent.com/29036171/147226567-2e310de7-d7a6-4d4b-a296-90a5109a76c3.png)
登录之后的界面按F12后显示如图。

**Comment by TheLostParadise** [comment]
> > > 23号左上角依然没有按钮。
> > 
> > 
> > 登录之后的界面按F12,弹出的界面看看有没有红字, 有的话截图看看
> > ![11](https://user-images.githubusercontent.com/29036171/147226567-2e310de7-d7a6-4d4b-a296-90a5109a76c3.png)
> > 登录之后的界面按F12后显示如图。

用chrome就有了，尴尬。

**Comment by oumu** [comment]
今天给同事弄也出现这个问题，最后发现是因为https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js在他那边打不开，换个地址就OK了。

**Comment by techxuexi21** [comment]
@oumu 是的，这个地址已经被和谐了

**Comment by techxuexi21** [comment]
已经修改代码里的地址。

**Comment by dsd137** [comment]
现在可以用暴力猴了是吧







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月21日(周五) 晚上7:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TechXueXi/techxuexi-js] 左上角没有开始按钮 (Issue #20)




 
已经修改代码里的地址。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
