### ISSUE TITLE
脚本能不能适配一下Kiwi Browser安卓浏览器？

### ISSUE THREAD

**Issue by drw2005** [TechXueXi/techxuexi-js#24]
### 清单

- [x] 我已经仔细阅读过 README.md
- [x] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [x] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [x] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**浏览器和版本**：Kiwi Browser v98.0.4758.20（ https://github.com/kiwibrowser/src.next ）

-----
<!--
下方三项，您不填写就直接删除那项。

## 详细描述
答：Kiwi Browser安卓浏览器也是Chromium内核，支持油猴安装脚本，理论上应该是支持咱们的这个脚本的。前两天尝试着安装了咱们的techxuexi-js，能运行，但是只能运行第一篇学习，结束后不自动进行下一篇学习。不知道是哪里的问题。

老大能不能百忙之中，抽空适配一下这个啊？有时侯不在电脑旁，用手机临时运行学习一下也不错。

感谢感谢！

**Comment by drw2005** [comment]
答：Kiwi Browser安卓浏览器也是Chromium内核，支持油猴安装脚本，理论上应该是支持咱们的这个脚本的。前两天尝试着安装了咱们的techxuexi-js，能运行，但是只能运行第一篇学习，结束后不自动进行下一篇学习。不知道是哪里的问题。

老大能不能百忙之中，抽空适配一下这个啊？有时侯不在电脑旁，用手机临时运行学习一下也不错。

感谢感谢！

**Comment by drw2005** [comment]
> 这个问题我解决掉了,原因是 默认情况下, chrome 只允许 window.close 关闭 window.open 打开的窗口,所以我们就要用window.open命令,在原地网页打开自身窗口再关上,就可以成功关闭了,具体做法是
> 
> 1.插入一段代码构建函数 closeWin()
> 
> ```
> function closeWin() {
>     try {
>          window.opener = window;
>          var win = window.open("","_self");
>          win.close();
>          top.close();
>     } catch (e) {
>         }
> 
> }
> ```
> 
>  2. 用 closeWin() 将原来脚本里的两处 window.close() 替换掉
> 
> 进行测试，平板上就可以一切正常地使用了。

太好了，兄弟能不能把修改好的techxuexi-js文件放上来，让大伙直接使用呢，感谢了。

**Comment by drw2005** [comment]
> 2\. closeWin()

太感谢了，这就测试一下去！

**Comment by drw2005** [comment]
> 这个问题我解决掉了,原因是 默认情况下, chrome 只允许 window.close 关闭 window.open 打开的窗口,所以我们就要用window.open命令,在原地网页打开自身窗口再关上,就可以成功关闭了,具体做法是
> 
> 1.插入一段代码构建函数 closeWin()
> 
> ```
> function closeWin() {
>     try {
>          window.opener = window;
>          var win = window.open("","_self");
>          win.close();
>          top.close();
>     } catch (e) {
>         }
> 
> }
> ```
> 
>  2. 用 closeWin() 将原来脚本里的两处 window.close() 替换掉
> 
> 进行测试，平板上就可以一切正常地使用了。

昨天晚上在Kiwi Browser上测试了一下（小米手机），好像还是不行，和之前一样啊。
大佬在手机上试了吗？能否放个完整的techxuexi-js文件上来？
感谢！

**Comment by skylovebeauty** [comment]
下官方最新脚本就行 作者大大已经整合进去了

**Comment by drw2005** [comment]
> 下官方最新脚本就行 作者大大已经整合进去了

那天就看到了，我用的就是最新的脚本。但是好像还是不行，不自动进行下一页。
你在手机上测试了吗？

**Comment by skylovebeauty** [comment]
我测试了确实是可行的。。。是用 pixel C 平板测试的

**Comment by drw2005** [comment]
> 我测试了确实是可行的。。。是用 pixel C 平板测试的

我现在也可以了，就是还是有些问题。学到大概38分左右，就不在加分了，一直在反复观看视频。

**Comment by skylovebeauty** [comment]
重复看视频的问题我也遇到了，原因大约是 找到的视频 不是最新的 所以一直不给加分

大约就是 

        console.log("还需要看" + n + "个视频")
        $.ajax({
            type: "GET",
            url: VideosUrl1,
            dataType: "json",
            success: function (data) {
                let j = 0;
                if (n == 6) {
                    for (let i = 0; i < n; i++) {
                        //如果有当天日期的,则加入
                        if (data[j].auditTime.indexOf(currDate) != -1) {
                            videos.push(data[j]);
                            j++;
                        } else {//否则跳出循环
                            break;
                        }
                    }
                }
                for (j; j < n; j++) {
                    let temp = parseInt(Math.random() * (data.length + 1), 10);
                    videos.push(data[temp]);
                }
                resolve('done');
            },
            error: function () {
                videos = [];
                resolve('done');
            }
        });

这一段里， 没有把当前日期的视频放进去，始终放进去的是 视频json 里面，中间的一段视频。。。不知道能不能改改
