### ISSUE TITLE
不显示开始学习按钮

### ISSUE THREAD

**Issue by ybdengzheng** [TechXueXi/techxuexi-js#28]
### 清单

- [X] 我已经仔细阅读过 README 说明 https://github.com/TechXueXi/techxuexi-js
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/techxuexi-js/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 脚本名称

不学习何以强国-beta.js

### 软件/源码版本

20220125

### 系统版本，包含位数

macos 12.2

### 浏览器版本

Microsoft Edge 版本 97.0.1072.69

### 油猴等插件和它的版本

油猴 v4.13

### 详细描述

刷新页面不显示开始学习按钮，开发者工具报错如下：
DevTools 无法加载源映射： 无法加载chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/md5.min.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME

**Comment by kt7a** [comment]
我的笔记本也碰到了类似的问题 - 没有显示”开始学习“按钮， 而台式机是正常的；
发现是下面列出的（14、15行代码）需要的资源不可访问：
    // @require      https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js
    // @require      https://cdn.bootcdn.net/ajax/libs/blueimp-md5/2.9.0/js/md5.min.js
把这两行用下面的语句替换，再保存就可以显示”开始学习“按钮了：
   // @require https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
   // @require https://cdn.jsdelivr.net/npm/blueimp-md5@2.9.0

**Comment by techxuexi21** [comment]
讨论合并到 https://github.com/TechXueXi/techxuexi-js/issues/29
