### ISSUE TITLE
视频学习不会自动关闭

### ISSUE THREAD

**Issue by Anony-Dino** [TechXueXi/techxuexi-js#30]
### 清单

- [x] 我已经仔细阅读过 README 说明 https://github.com/TechXueXi/techxuexi-js
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/techxuexi-js/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 脚本名称

不学习何以强国.js

### 软件/源码版本

20220125

### 系统版本，包含位数

Mac Monterey

### 浏览器版本

Chrome 97.0.4692.71

### 油猴等插件和它的版本

4.14

### 详细描述

视频学习识别视频组件时判断优化
页面会生成一个 `src="about:blank"` 的空iframe
将 `getVideoTag` 函数中的 `if (iframe)`判断 改为 `if (iframe.innerHTML)` 即可

**Comment by techxuexi21** [comment]
谢谢。还没有 windows 的同志没有反馈这个，视频学习不会自动关闭 可能仅是mac 的问题，加个判断 mac的好一些

**Comment by Zypeong** [comment]
你好，Windows 有同样的情况，最新的Chrome

**Comment by techxuexi21** [comment]
已修复代码

**Comment by techxuexi21** [comment]
@techxuexi21 收到反馈，直接这样修改的话，会使部分用户卡在视频任务中，始终提示“正在初始化”

现在如果出现此问题可以回退这个修改 https://github.com/TechXueXi/techxuexi-js/commit/a73672849e354fb80f2fb297869c459bb14faf84#diff-D508E42FDF515B3B195344FDCD06BA19

**Comment by Anony-Dino** [comment]
> @techxuexi21 收到反馈，直接这样修改的话，会使部分用户卡在视频任务中，始终提示“正在初始化”
> 
> 现在如果出现此问题可以回退这个修改 [a736728#diff-D508E42FDF515B3B195344FDCD06BA19](https://github.com/TechXueXi/techxuexi-js/commit/a73672849e354fb80f2fb297869c459bb14faf84#diff-D508E42FDF515B3B195344FDCD06BA19)

那情况正好跟Mac相反, 这个问题的起因就是Mac卡在"正在初始化" 上, Win我没有试.

**Comment by techxuexi21** [comment]
最新版已经修复

**Comment by drw2005** [comment]
> 最新版已经修复

Chrome 97.0.4692.99用最新脚本仍然出现不自动关闭的情况，而且还会再打开一个新标签。
