### ISSUE TITLE
脚本每天做满给多少积分 

### ISSUE THREAD

**Issue by cy920820** [TechXueXi/techxuexi-js#53]
### 清单

- [X] 我已经仔细阅读过 README 说明 https://github.com/TechXueXi/techxuexi-js
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/techxuexi-js/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 脚本名称

不学习何以强国.js

### 软件/源码版本

20220206

### 系统版本，包含位数

Mac OS 12.4

### 浏览器版本

chrome v103.0.5060.53

### 油猴等插件和它的版本

V4.16.1

### 详细描述

请问脚本每天做满任务给多少积分？？？

**Comment by Technicalflight** [comment]
45还是60来着

**Comment by cmliu22** [comment]
今天试了下35分
