### ISSUE TITLE
版本号一直未更新，Tampermonkey 无法自动更新脚本

### ISSUE THREAD

**Issue by leic4u** [TechXueXi/techxuexi-js#74]
### 清单

- [X] 我已经仔细阅读过 README 说明 https://github.com/TechXueXi/techxuexi-js
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/techxuexi-js/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 脚本名称

不学习何以强国.js

### 软件/源码版本

20220214

### 系统版本，包含位数

Windows11 x64 22H2 22623.1245

### 浏览器版本

Chrome 109.0.5414.120

### 油猴等插件和它的版本

Tampermonkey 4.19.6176

### 详细描述

最新的 JS 脚本版本号还是写的 `20220214`，导致 Tampermonkey 不能自动更新，每次都只能手动复制脚本粘贴进去。
如果可以，请更新下版本号，谢谢。

**Comment by justin0705** [comment]
可以自己改的

**Comment by leic4u** [comment]
> 可以自己改的

每次更新后自己改成20220213吗😂

**Comment by leic4u** [comment]
已开始更新版本号，感谢修复。

**Comment by Nu11able** [comment]
我也遇到这个问题，我服务器上的版本是2.0.0,客户端的版本是1.0.0，每次去检查更新服务器会把整个脚本返回，然后每次都提示“暂时没有更新，等会儿再来吧~”
```
// @updateURL    https://127.0.0.1:4567/client.js
// @downloadURL  https://127.0.0.1:4567/client.js
```
这两个地址我都返回的是整个脚本文件，还是说对于updateURL的请求我要返回点别的

**Comment by AmanITal** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Nu11able** [comment]
> 我也遇到这个问题，我服务器上的版本是2.0.0,客户端的版本是1.0.0，每次去检查更新服务器会把整个脚本返回，然后每次都提示“暂时没有更新，等会儿再来吧~”
> 
> ```
> // @updateURL    https://127.0.0.1:4567/client.js
> // @downloadURL  https://127.0.0.1:4567/client.js
> ```
> 
> 这两个地址我都返回的是整个脚本文件，还是说对于updateURL的请求我要返回点别的

解决了，因为脚本一开始是复制到本地然后保存的，所以哪怕加了`updateUrl`也没用，后面把本地脚本删了，重新从url导入就正常了
