### ISSUE TITLE
最近网页答题需要滑动验证码，求更

### ISSUE THREAD

**Issue by sjtuwater** [TechXueXi/techxuexi-js#8]
最近网页自动答题需要滑动验证码块，求更

**Comment by latia0sama** [comment]
> 最近网页自动答题需要滑动验证码块，求更

我也是

**Comment by fatfish516** [comment]
最近遇到网页自动答题需要滑动验证码块，然后界面就卡在自动答题页面不动了

**Comment by suxin0203** [comment]
同

**Comment by techxuexi21** [comment]
@suxin0203 手动滑可以通过吗？

**Comment by suxin0203** [comment]
可以 

> @suxin0203 手动滑可以通过吗？
可以

**Comment by zwyzzz888** [comment]
同

**Comment by Fireselector** [comment]
手动滑不过去的怎么办？

**Comment by MargaretteMoss** [comment]
```html
<html>
 <body id="body-body">
   <div class="nc-xi-container">
    <div id="swiper_valid" class="nc-container" data-nc-idx="1"> 
     <div id="nc_1_wrapper" class="nc_wrapper"> 
      <div id="nc_1_n1t" class="nc_scale"> 
       <div id="nc_1__bg" class="nc_bg" style="width: 0px;"></div> 
       <span id="nc_1_n1z" class="nc_iconfont btn_slide" style="left: 0px;"></span> 
       <div id="nc_1__scale_text" class="scale_text slidetounlock">
        <span class="nc-lang-cnt" data-nc-lang="_startTEXT">请按住滑块，拖动到最右边</span>
       </div> 
       <div id="nc_1_clickCaptcha" class="clickCaptcha"> 
        <div class="clickCaptcha_text"> 
         <b id="nc_1__captcha_text" class="nc_captch_text"></b> 
         <i id="nc_1__btn_2" class="nc_iconfont nc_btn_2 btn_refresh"></i> 
        </div> 
        <div class="clickCaptcha_img"></div> 
        <div class="clickCaptcha_btn"></div> 
       </div> 
       <div id="nc_1_imgCaptcha" class="imgCaptcha"> 
        <div class="imgCaptcha_text">
         <input id="nc_1_captcha_input" maxlength="6" type="text" style="ime-mode:disabled" />
        </div> 
        <div class="imgCaptcha_img" id="nc_1__imgCaptcha_img"></div> 
        <i id="nc_1__btn_1" class="nc_iconfont nc_btn_1 btn_refresh" onclick="document.getElementById('nc_1__imgCaptcha_img').children[0].click()"></i> 
        <div class="imgCaptcha_btn"> 
         <div id="nc_1__captcha_img_text" class="nc_captcha_img_text"></div> 
         <div id="nc_1_scale_submit" class="nc_scale_submit"></div> 
        </div> 
       </div> 
       <div id="nc_1_cc" class="nc-cc"></div> 
       <i id="nc_1__voicebtn" tabindex="0" role="button" class="nc_voicebtn nc_iconfont" style="display:none"></i> 
       <b id="nc_1__helpbtn" class="nc_helpbtn"><span class="nc-lang-cnt" data-nc-lang="_learning">了解新功能</span></b> 
      </div> 
      <div id="nc_1__voice" class="nc_voice"></div> 
     </div> 
    </div>
   </div>
  </div>
 </body>
</html>
```


我拷贝了核心代码片段，并且测试了一下。我在F12窗口里面将第7行和第8行的`width: 0px`和`left: 0px`从0改为260，然后再点一下滑动块就通过验证了。所以优化逻辑应该是第7行和第8行的`width: 0px`和`left: 0px`从0变为260，然后模拟点击一下25行的`nc_1__btn_1`然后就可以了。

@techxuexi21 有空可以帮忙优化一下代码吗？谢谢！

**Comment by MargaretteMoss** [comment]
> 手动滑不过去的怎么办？ 滑块报错： ![](https://camo.githubusercontent.com/8b4c72f28c8a8010b1f21e2cb842aac2456236b41ac52a0a7eed59a8deec0522/68747470733a2f2f73312e617831782e636f6d2f323032322f30342f30372f4c5348506d392e6a7067)

你这个应该是超时了。

**Comment by zhaotuo0815** [comment]
> ```
> <html>
>  <body id="body-body">
>    <div class="nc-xi-container">
>     <div id="swiper_valid" class="nc-container" data-nc-idx="1"> 
>      <div id="nc_1_wrapper" class="nc_wrapper"> 
>       <div id="nc_1_n1t" class="nc_scale"> 
>        <div id="nc_1__bg" class="nc_bg" style="width: 0px;"></div> 
>        <span id="nc_1_n1z" class="nc_iconfont btn_slide" style="left: 0px;"></span> 
>        <div id="nc_1__scale_text" class="scale_text slidetounlock">
>         <span class="nc-lang-cnt" data-nc-lang="_startTEXT">请按住滑块，拖动到最右边</span>
>        </div> 
>        <div id="nc_1_clickCaptcha" class="clickCaptcha"> 
>         <div class="clickCaptcha_text"> 
>          <b id="nc_1__captcha_text" class="nc_captch_text"></b> 
>          <i id="nc_1__btn_2" class="nc_iconfont nc_btn_2 btn_refresh"></i> 
>         </div> 
>         <div class="clickCaptcha_img"></div> 
>         <div class="clickCaptcha_btn"></div> 
>        </div> 
>        <div id="nc_1_imgCaptcha" class="imgCaptcha"> 
>         <div class="imgCaptcha_text">
>          <input id="nc_1_captcha_input" maxlength="6" type="text" style="ime-mode:disabled" />
>         </div> 
>         <div class="imgCaptcha_img" id="nc_1__imgCaptcha_img"></div> 
>         <i id="nc_1__btn_1" class="nc_iconfont nc_btn_1 btn_refresh" onclick="document.getElementById('nc_1__imgCaptcha_img').children[0].click()"></i> 
>         <div class="imgCaptcha_btn"> 
>          <div id="nc_1__captcha_img_text" class="nc_captcha_img_text"></div> 
>          <div id="nc_1_scale_submit" class="nc_scale_submit"></div> 
>         </div> 
>        </div> 
>        <div id="nc_1_cc" class="nc-cc"></div> 
>        <i id="nc_1__voicebtn" tabindex="0" role="button" class="nc_voicebtn nc_iconfont" style="display:none"></i> 
>        <b id="nc_1__helpbtn" class="nc_helpbtn"><span class="nc-lang-cnt" data-nc-lang="_learning">了解新功能</span></b> 
>       </div> 
>       <div id="nc_1__voice" class="nc_voice"></div> 
>      </div> 
>     </div>
>    </div>
>   </div>
>  </body>
> </html>
> ```
> 
> 我拷贝了核心代码片段，并且测试了一下。我在F12窗口里面将第7行和第8行的`width: 0px`和`left: 0px`从0改为260，然后再点一下滑动块就通过验证了。所以优化逻辑应该是第7行和第8行的`width: 0px`和`left: 0px`从0变为260，然后模拟点击一下25行的`nc_1__btn_1`然后就可以了。
> 
> @techxuexi21 有空可以帮忙优化一下代码吗？谢谢！

有最新的代码吗？非常感谢

**Comment by langjiahui** [comment]
同求

**Comment by left0ver** [comment]
> ```
> <html>
>  <body id="body-body">
>    <div class="nc-xi-container">
>     <div id="swiper_valid" class="nc-container" data-nc-idx="1"> 
>      <div id="nc_1_wrapper" class="nc_wrapper"> 
>       <div id="nc_1_n1t" class="nc_scale"> 
>        <div id="nc_1__bg" class="nc_bg" style="width: 0px;"></div> 
>        <span id="nc_1_n1z" class="nc_iconfont btn_slide" style="left: 0px;"></span> 
>        <div id="nc_1__scale_text" class="scale_text slidetounlock">
>         <span class="nc-lang-cnt" data-nc-lang="_startTEXT">请按住滑块，拖动到最右边</span>
>        </div> 
>        <div id="nc_1_clickCaptcha" class="clickCaptcha"> 
>         <div class="clickCaptcha_text"> 
>          <b id="nc_1__captcha_text" class="nc_captch_text"></b> 
>          <i id="nc_1__btn_2" class="nc_iconfont nc_btn_2 btn_refresh"></i> 
>         </div> 
>         <div class="clickCaptcha_img"></div> 
>         <div class="clickCaptcha_btn"></div> 
>        </div> 
>        <div id="nc_1_imgCaptcha" class="imgCaptcha"> 
>         <div class="imgCaptcha_text">
>          <input id="nc_1_captcha_input" maxlength="6" type="text" style="ime-mode:disabled" />
>         </div> 
>         <div class="imgCaptcha_img" id="nc_1__imgCaptcha_img"></div> 
>         <i id="nc_1__btn_1" class="nc_iconfont nc_btn_1 btn_refresh" onclick="document.getElementById('nc_1__imgCaptcha_img').children[0].click()"></i> 
>         <div class="imgCaptcha_btn"> 
>          <div id="nc_1__captcha_img_text" class="nc_captcha_img_text"></div> 
>          <div id="nc_1_scale_submit" class="nc_scale_submit"></div> 
>         </div> 
>        </div> 
>        <div id="nc_1_cc" class="nc-cc"></div> 
>        <i id="nc_1__voicebtn" tabindex="0" role="button" class="nc_voicebtn nc_iconfont" style="display:none"></i> 
>        <b id="nc_1__helpbtn" class="nc_helpbtn"><span class="nc-lang-cnt" data-nc-lang="_learning">了解新功能</span></b> 
>       </div> 
>       <div id="nc_1__voice" class="nc_voice"></div> 
>      </div> 
>     </div>
>    </div>
>   </div>
>  </body>
> </html>
> ```
> 
> 我拷贝了核心代码片段，并且测试了一下。我在F12窗口里面将第7行和第8行的`width: 0px`和`left: 0px`从0改为260，然后再点一下滑动块就通过验证了。所以优化逻辑应该是第7行和第8行的`width: 0px`和`left: 0px`从0变为260，然后模拟点击一下25行的`nc_1__btn_1`然后就可以了。
> 
> @techxuexi21 有空可以帮忙优化一下代码吗？谢谢！


我尝试了一下，貌似不起作用，最后一步模拟点击`nc_1__btn_1`有问题，
```
 <div class="imgCaptcha_img" id="nc_1__imgCaptcha_img"></div> 
 <i id="nc_1__btn_1" class="nc_iconfont nc_btn_1 btn_refresh" onclick="document.getElementById('nc_1__imgCaptcha_img').children[0].click()"></i> 
```
这里可以看到`nc_1__btn_1`上有一个click事件，点击事件中获取了`nc_1__imgCaptcha_img`下面的第一个子元素，但是`nc_1__imgCaptcha_img`元素下面并没有子元素，我猜想是不是使用了js自动添加了，如果是js自动添加的，那么是在什么情况下添加的

**Comment by Masakazu7709** [comment]
> > ```
> > <html>
> >  <body id="body-body">
> >    <div class="nc-xi-container">
> >     <div id="swiper_valid" class="nc-container" data-nc-idx="1"> 
> >      <div id="nc_1_wrapper" class="nc_wrapper"> 
> >       <div id="nc_1_n1t" class="nc_scale"> 
> >        <div id="nc_1__bg" class="nc_bg" style="width: 0px;"></div> 
> >        <span id="nc_1_n1z" class="nc_iconfont btn_slide" style="left: 0px;"></span> 
> >        <div id="nc_1__scale_text" class="scale_text slidetounlock">
> >         <span class="nc-lang-cnt" data-nc-lang="_startTEXT">请按住滑块，拖动到最右边</span>
> >        </div> 
> >        <div id="nc_1_clickCaptcha" class="clickCaptcha"> 
> >         <div class="clickCaptcha_text"> 
> >          <b id="nc_1__captcha_text" class="nc_captch_text"></b> 
> >          <i id="nc_1__btn_2" class="nc_iconfont nc_btn_2 btn_refresh"></i> 
> >         </div> 
> >         <div class="clickCaptcha_img"></div> 
> >         <div class="clickCaptcha_btn"></div> 
> >        </div> 
> >        <div id="nc_1_imgCaptcha" class="imgCaptcha"> 
> >         <div class="imgCaptcha_text">
> >          <input id="nc_1_captcha_input" maxlength="6" type="text" style="ime-mode:disabled" />
> >         </div> 
> >         <div class="imgCaptcha_img" id="nc_1__imgCaptcha_img"></div> 
> >         <i id="nc_1__btn_1" class="nc_iconfont nc_btn_1 btn_refresh" onclick="document.getElementById('nc_1__imgCaptcha_img').children[0].click()"></i> 
> >         <div class="imgCaptcha_btn"> 
> >          <div id="nc_1__captcha_img_text" class="nc_captcha_img_text"></div> 
> >          <div id="nc_1_scale_submit" class="nc_scale_submit"></div> 
> >         </div> 
> >        </div> 
> >        <div id="nc_1_cc" class="nc-cc"></div> 
> >        <i id="nc_1__voicebtn" tabindex="0" role="button" class="nc_voicebtn nc_iconfont" style="display:none"></i> 
> >        <b id="nc_1__helpbtn" class="nc_helpbtn"><span class="nc-lang-cnt" data-nc-lang="_learning">了解新功能</span></b> 
> >       </div> 
> >       <div id="nc_1__voice" class="nc_voice"></div> 
> >      </div> 
> >     </div>
> >    </div>
> >   </div>
> >  </body>
> > </html>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我拷贝了核心代码片段，并且测试了一下。我在F12窗口里面将第7行和第8行的和从0改为260，然后再点一下滑动块就通过验证了。所以优化逻辑应该是第7行和第8行的和从0变为260，然后模拟点击一下25行的然后就可以了。`width: 0px``left: 0px``width: 0px``left: 0px``nc_1__btn_1`
> > @techxuexi21 有空可以帮忙优化一下代码吗？谢谢！
> 
> 我尝试了一下，貌似不起作用，最后一步模拟点击有问题，`nc_1__btn_1`
> 
> ```
>  <div class="imgCaptcha_img" id="nc_1__imgCaptcha_img"></div> 
>  <i id="nc_1__btn_1" class="nc_iconfont nc_btn_1 btn_refresh" onclick="document.getElementById('nc_1__imgCaptcha_img').children[0].click()"></i> 
> ```
> 
> 这里可以看到上有一个click事件，点击事件中获取了下面的第一个子元素，但是元素下面并没有子元素，我猜想是不是使用了js自动添加，如果是js自动添加的，那么是在什么情况下添加的`nc_1__btn_1``nc_1__imgCaptcha_img``nc_1__imgCaptcha_img`

请问这个代码要怎么用呢

**Comment by my1487** [comment]
手动能划
